### ISSUE TITLE
Why this updater is sending my Maxmind API key to a server located in Russia?

### ISSUE THREAD

**Issue by AutisticShark** [tronovav/geoip2-update#12]
The hard-coded API endpoint in this updater was changed to `https://www.geodbase-update.com/api/v1/edition` last year, right after all older commit messages were purged. The domain `www.geodbase-update.com` was resolved to an IPv4 address `62.113.98.134`, which is located in Petersburg, Russia. It appears that this API will request the MaxMind server verify the validity of the API key, and then cache the key on this Russian server, every time the updater requests to download a new update, the database file will be returned from a Yandex cloud endpoint, this behavior is far from `the library will check for updates on the "maxmind.com" server and update the Geoip2 databases if necessary` stated in the project readme.

Please explain yourself.

**Comment by danielsreichenbach** [comment]
I made a fork and published `v2.4.0` on <https://packagist.org/packages/danielsreichenbach/geoip2-update>.

The forked package is using the official MaxMind API (same endpoints like their official geoip-updater tool), and also fixed some other small issues.

My version requires an additional parameter though: `account_id`. The MaxMind API endpoints seem to require both account ID and license key.

Would be nice to know why the author is using this domain, and why he is collecting peoples license keys.

**Comment by tronovav** [comment]
No keys or any other identification data are collected, cached or stored on the side of the service https://www.geodbase-update.com

**Comment by cameron1729** [comment]
@tronovav security concerns aside, I'd like to point out that there are other issues with the way this works. Sometimes, for  no obvious reason, a file of size 0 bytes is returned.  For example this [request](https://www.geodbase-update.com/api/v1/edition/download?request_id=pc-mfE8CPoQ2FX-ZvfYO6ca7EnenpQ8J)
