### ISSUE TITLE
Maxmind R2 presigned URLs causing download to break

### ISSUE THREAD

**Issue by microcrash** [tronovav/geoip2-update#13]
As of Wednesday, April 24, 2024, Maxmind is using R2 presigned URLs for all database downloads in order to increase the security and reliability of our services. See page here: https://support.maxmind.com/hc/en-us/articles/4408216129947-Download-and-Update-Databases. Since this adjustment was made, updates have been failing where I get the following fatal error:

`Fatal error: Uncaught UnexpectedValueException: internal corruption of phar "/www/includes/maxmind/GeoIP2-Country.tar.gz" (truncated entry) in /webroot/h/a/hadmi001/user_root/composer/vendor/tronovav/geoip2-update/src/Client.php:292
Stack trace:
#0 /user_root/composer/vendor/tronovav/geoip2-update/src/Client.php(292): PharData->__construct()
#1 /user_root/composer/vendor/tronovav/geoip2-update/src/Client.php(189): tronovav\GeoIP2Update\Client->extract() #2 /user_root/composer/vendor/tronovav/geoip2-update/src/Client.php(99): tronovav\GeoIP2Update\Client->updateEdition()
#3 /www/includes/maxmind/update.php(12): tronovav\GeoIP2Update\Client->run()
#4 {main}
thrown in /user_root/composer/vendor/tronovav/geoip2-update/src/Client.php on line 292`

- OS: Linux Webhost
- PHP version: 8.1
- `tronovav/geoip2-update: v2.3.1
- Composer version: 2.7.2

I notice that the tar.gz file left on my server is a 0 kb file. I'm assuming the adjustments by Maxmind is now being blocked when it is attempting to download. I am unsure if my webhost is causing the issue, or if the software package is able to handle the new endpoints.

**Comment by AutisticShark** [comment]
https://github.com/tronovav/geoip2-update/issues/12

**Comment by microcrash** [comment]
> #12

Thank you! I switched to https://github.com/danielsreichenbach/geoip2-update and got everything working again.
