### ISSUE TITLE
unable to download files

### ISSUE THREAD

**Issue by gangiaemi** [tronovav/geoip2-update#3]
**Describe the bug**

hi, im using this package to download updated free databases 
I follow all steps but i receive this message : Edition ID: "GeoLite2-Country" not found in maxmind.com.
This message is in Client.php # 160.

**To Reproduce**
This is what i done:
1. Create file geoupdate.php by example in documentation
2. Call this script from browser :  http://mydomain.com/geoupdate.php
4. See Message on browser screen

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser firefox 
 - Version 88

**Additional context**
I tried to call generated url from Client.php in headers method link #226.
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&suffix=tar.gz&license_key=mylicense
This works.
Thanks in advance

**Comment by tronovav** [comment]
Please update `tronovav / geoip2-update` to the latest version. Now the latest version is v2.1.5

In this release, we have added in the answer a detailed description of the causes of errors in downloading database updates.

It seems to us that you simply made a mistake when specifying the license key in the client configuration.

Even if this is not the case, you will now see more detailed information about your cause.
