### ISSUE TITLE
Add GeoIP2-ISP support

### ISSUE THREAD

**Issue by julienmru** [tronovav/geoip2-update#7]
Kindly consider adding GeoIP2-ISP support : )

I added locally the following in `$remoteEditions` and it works just fine:
```
        'GeoIP2-ISP' => self::TYPE_MMDB,
```

Thanks : )

**Comment by tronovav** [comment]
Excellent!
We will definitely add it in the next release.
It would be great if you have more requests for other database files. Let's add them too.
Next release coming soon :)
