### ISSUE TITLE
Version 2.3.0 to packagist

### ISSUE THREAD

**Issue by midweste** [tronovav/geoip2-update#8]
**Describe the bug**
Updates never got pushed to packagist.  Thank you for the package :)

**Comment by midweste** [comment]
FYI - the packagist latest version 2.2.4 seems to be returning an error on composer install/update, however the version here from Github works without issue.

> tronovav\GeoIP2Update\ComposerClient::run
  - Downloading GeoLite2-City: [============================] 100%
GeoLite2-Country does not need to be updated.
GeoIP2 database update errors:
  - GeoLite2-City: download error. Remote server response code "200".

**Comment by tronovav** [comment]
We noticed revision conflicts between github and packagist. Now you can update everywhere. Thank you!
